### ISSUE TITLE
Issues regarding running MRBRT.fit_model

### ISSUE THREAD

**Issue by RuijingNi** [ihmeuw-msca/mrtool#47]
**_Dear MRTool Developers,

Recently I'm trying to use this tool to predict the exposure-response curves, but I have encountered some issues regarding the codes.

I have tested a sample you give in this website: https://mrtool.readthedocs.io/en/latest/examples/example_linear.html
Here shows my codes:_** 
#-----------------------------------------------------------------
# @Ruijing Ni(Ruijing.Ni@mpic.de)
# Code for fitting exposure-response function curve

from mrtool import MRData
from mrtool import LinearCovModel
from mrtool import MRBRT
import pandas as pd
from limetr import LimeTr

df=pd.DataFrame.from_dict(
  {'y':pd.Series([0.20,0.29,0.09,0.14,0.40]),
   'x':pd.Series([0.0 ,0.1 ,0.2 ,0.3 ,0.4 ]),
   'y_se':pd.Series([0.1,0.1,0.1,0.1,0.1]),
   'study_id':pd.Series(['A','A','B','C','D'])
  }
)

#allocate MRData object
data=MRData()

#Data delivery
data.load_df(
    df,
    col_obs='y',
    col_covs=['x'],
    col_obs_se='y_se',
    col_study_id='study_id'
)

#create covariate models
cov_intercept = LinearCovModel('intercept', use_re=True)
cov_x = LinearCovModel('x')

#create fit model
model = MRBRT(
    data,
    [cov_intercept, cov_x]
)
model.fit_model()
#-----------------------------------------------------------------

_**Then error occurs:**_ 
#-----------------------------------------------------------------
Traceback (most recent call last):
  File "/raven/u/nirj/Python/Health_Impact/pro/Asthma_updated/dataset/../pro/data_test_MRData_t.py", line 39, in <module>
    model.fit_model()
  File "/u/nirj/.local/lib/python3.9/site-packages/mrtool-0.0.1-py3.9.egg/mrtool/core/model.py", line 272, in fit_model
    self.lt = LimeTr(n, k_beta, k_gamma,
TypeError: __init__() got an unexpected keyword argument 'S'
#-----------------------------------------------------------------

_**I have checked the function library 'LimeTr' called here,**_ 
def fit_model(self, **fit_options):
#-----------------------------------------------------------------
        """Fitting the model through limetr.

        ...

        **# create limetr object
        self.lt = LimeTr(n, k_beta, k_gamma,
                         y, x_fun, x_fun_jac, z_mat, S=s,
                         C=c_fun, JC=c_fun_jac, c=c_vec,
                         H=h_fun, JH=h_fun_jac, h=h_vec,
                         uprior=uprior, gprior=gprior, lprior=lprior,
                         inlier_percentage=self.inlier_pct)**

       ...
#-----------------------------------------------------

**_As the text shown in bold, a lot of variables are passing to LimeTr. But I found that, in the lastest version of LimeTr (v0.1.1), variables are not defined and passed in this way (shown below). While in the earliest version, it does (shown below)._**
#----lastest version 0.1.1 LimeTr--------------------
def __init__(self,
                 data: Data,
                 fevar: FeVariable,
                 revar: ReVariable,
                 inlier_pct: float = 1.0):
        """
#----lastest version 0.0.1 LimeTr--------------------
class LimeTr:
    def __init__(self, n, k_beta, k_gamma, Y, F, JF, Z,
                 S=None, share_obs_std=False,
                 C=None, JC=None, c=None,
                 H=None, JH=None, h=None,
                 uprior=None, gprior=None, lprior=None,
                 certain_inlier_id=None,
                 inlier_percentage=1.0):
        """
#-----------------------------------------------------

**_So I guess the error occurs due to the version update or version compatibility issues. It seems that, MRTool has not been updated to adapt to the updates of LimeTr. I have tried to install the earliest version of LimeTr (v0.0.1), but it always failed.

Do you have any idea or advice on this? How can I successfully use MRTool? I'm looking forward to your replies.

Many thanks,
Ruijing Ni_**

**Comment by zhengp0** [comment]
Thanks very much for reaching out @RuijingNi! Sorry we replied to this message embarrassingly slow. The error you raised are due to the version incompatibility problem. We recently published new versions of `mrtool` on PyPI where we explicitly specify the version of the `limetr`.

https://github.com/ihmeuw-msca/mrtool/blob/main/pyproject.toml#L15

Right now if you do
```
pip install --upgrade mrtool
```
The correct version of the `limetr` will be installed. Give it a try and let me know if you have more issues.
